### ISSUE TITLE
Redistrubute or update app on f-droid

### ISSUE THREAD

**Issue by sphrak** [firetech/PactrackDroid#16]
Hi @firetech,
This app was last updated 2011 on F-droid.
But there exists a version from 2016 and it still works so I dont see why this hasnt been updated? 

We can submit a request for packaging here https://gitlab.com/fdroid/rfp/issues incase you cant do it yourself anymore.

Ideally the old version needs to be removed. What do you think?

**edit**: I realize now after reading the source that the reason you havent done it is because the packaged version is not open source because of the API key issue. 

Kindly,

**Comment by firetech** [comment]
I am not the one who uploaded the app to F-droid in the first place. Furthermore, I unpublished the app from the Google Play Store some months ago for two reasons:

1. The official PostNord app does the same thing (and more), better. For example, it has automatic addition of packages based on phone number and email.
2. The quotas for free usage PostNord's API were severely lowered (from 10000 calls per day to 500), making it basically impossible to use the app without your own API key.

Because of the second issue, compiling PactrackDroid yourself is the only feasible option if you still want to use it in its current state, and since I'm not even using it myself anymore, I don't see much reason to update the app. This makes it currently quite irrelevant to upload the latest version of the app to any app store/repository.

_However_, the version on F-droid is 1.3.1, using another API (that basically only finds packages, not registered letters, "varubrev" etc.). The last version to use that API (and included much more modern UI) was 1.6 (revision e46fe1857beb23bf12015ea5ea523edf731d9da9), which (in theory) should still work. That version was actually never released, since I started working on a GUI revamp at about the same time (it does include some bug fixes over 1.5). A more safer revision may be 46eb6b5cae4b8fd2cc60ce0681c2c5ddea13d26b, which is what was released as 1.5.

Since I wasn't involved in putting PactrackDroid on F-droid at all, I'm not sure how to tell them to update, but if you want to do it, that's fine wih me.
